export const MIN_INSTALLMENTS = 1
export const MAX_INSTALLMENTS = 24
export const DEFAULT_CARD_FEE_PERCENT = 3.5
export const DEFAULT_ANTICIPATION_FEE_PERCENT = 2.0
export const DEFAULT_DESIRED_MARGIN_PERCENT = 30
